#! /bin/sh
source ~/.config/colors.ini

monitorCount=$(xrandr -d :0 -q | grep ' connected' | wc -l)
echo "${monitorCount}"

if [ ${monitorCount} = 1 ]
then
  echo "mc1 ${monitorCount}"
  bspc monitor eDP-1-1 -d I II III Iv V Vi VII
else
  echo "mc2 ${monitorCount}"
  bspc monitor eDP-1-1 -d I II
  bspc monitor HDMI-0 -d III IV
  bspc monitor DP-0 -d V VI VII
fi

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          20
bspc config focused_border_color $lightGreen
bspc config normal_border_color $fg
bspc config active_border_color $orange

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox                                            desktop='^1' follow="on"
bspc rule -a Slack                                              desktop='^2' follow="off"
bspc rule -a discord                                            desktop='^2' follow="off"
bspc rule -a Termite                                            desktop='^3' follow="on"
bspc rule -a Termite:sxhkd_keys                                 desktop='^'               state=floating
bspc rule -a Steam                                              desktop='^4' follow="on"
bspc rule -a Lutris                                             desktop='^4'
bspc rule -a Google\ Play\ Music\ Desktop\ Player               desktop='^4'
bspc rule -a Spotify\ Premium                                            desktop='^4'
bspc rule -a Spotify                                            desktop='^4'
bspc rule -a spotify                                            desktop='^4'
bspc rule -a figma-linux                                        desktop='^5' follow="on"

sh -c "~/./.monitor"
sh -c "$HOME/.config/polybar/launch.sh"
sh -c "feh --bg-scale ~/.wallpapers/wallhaven-n65epw.png"
sh -c "pgrep sxhkd || killall -q sxhkd || sxhkd -c ~/.config/sxhkd/sxhkdrc &"
sh -c "pgrep dunst || killall -q dunst || dunst -c ~/.config/dunst/dunstrc &"
