#! /bin/sh
source ~/.config/colors.ini

bspc monitor eDP-1-1 -d I II
bspc monitor HDMI-0 -d III IV V VI

bspc config border_width         1
bspc config window_gap          50
bspc config focused_border_color $lightGreen
bspc config normal_border_color $fg
bspc config active_border_color $orange

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1' follow="on"
bspc rule -a Slack desktop='^2' follow="off"
bspc rule -a discord desktop='^2' follow="off"
bspc rule -a Termite desktop='^3' follow="on"
bspc rule -a Steam desktop='^4' follow="on"
bspc rule -a Lutris desktop='^4'
bspc rule -a Termite:sxhkd_keys state=floating desktop='^'

sh -c "~/./.monitor"
sh -c "feh --bg-scale ~/.wallpapers/wallhaven-n65epw.png"
sh -c "$HOME/.config/polybar/launch.sh"
sh -c "pgrep sxhkd || killall -q sxhkd || sxhkd -c ~/.config/sxhkd/sxhkdrc &"
sh -c "pgrep dunst || killall -q dunst || dunst -c ~/.config/dunst/dunstrc &"
