#! /bin/sh
source ~/.config/colors.ini

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII
#bspc monitor DP-1 -d VI VII VIII

bspc config border_width         1
bspc config window_gap          10
bspc config focused_border_color $lightGreen
bspc config normal_border_color $fg
bspc config active_border_color $orange
bspc config focus_follows_pointer true

bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1'
bspc rule -a "Spotify Premium" desktop='^3'
bspc rule -a "Slack" desktop='^3'
bspc rule -a Termite desktop='^4' follow="on" 
bspc rule -a Termite:pulsemixer desktop='^' state="floating" follow="off"


sh -c "feh --bg-scale ~/downloads/wallhaven-39wol3.png &"
sh -c "$HOME/.config/polybar/launch.sh &"
sh -c "pgrep sxhkd || killall -q sxhkd || sxhkd -c ~/.config/sxhkd/sxhkdrc &"
sh -c "xrandr --output eDP-1 --mode 1920x1080 --rate 144 &"
xsetroot -cursor_name left_ptr
#xrandr --output DP-1 --auto --right-of eDP-1
xrandr --output HDMI-2 --auto --right-of eDP-1
#sh -c "$HOME/.config/bspwm/swallow.py"
#termite -e "cat $HOME/stuff/notes.md"
#sh -c "pgrep dunst || killall -q dunst || dunst -c ~/.config/dunst/dunstrc &"
